### ISSUE TITLE
Weird RSA - tip

### ISSUE THREAD

**Issue by acr92** [W3ndige/w3ndige.github.io#1]
Hey,

I saw your solution for WeirdRSA at https://github.com/W3ndige/w3ndige.github.io/blob/3d26f18c9a97a95c7c09512c019f2f629b6adb2c/_posts/2017-04-14-picoctf-weird-rsa.markdown

Thanks for the explaination, but I found a slightly simpler solution:

```
from Crypto.Util.number import long_to_bytes

plain = pow(c, dp, p)
print "decrypted: {}".format(long_to_bytes(plain))
```

You can use dq, q instead of dp, p, and it works just as fine.

Also, while I'm at it, I hope you could submit your writeups at https://ctftime.org/ - it helps people searching for writeups :)

Thanks!

**Comment by W3ndige** [comment]
Wow, that's a lot simpler but I think it's essential to understand RSA crypto just as it is, then start using crypto libraries. And yeah, I'll submit them to ctfime as soon as possible. 

Thanks for the tip!
